from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class AddonAction:
    name: str
    command: tuple[str, ...]
    open_terminal: bool


_DEFAULT_TERMINAL = ("x-terminal-emulator", "-e")


def _groovy_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("'", "\\'")
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )
    return f"'{escaped}'"


def build_addon_actions(binary_command: Sequence[str]) -> tuple[AddonAction, ...]:
    base = tuple(str(part) for part in binary_command)
    return (
        AddonAction("Validate map", (*base, "validate"), False),
        AddonAction("Explain map", (*base, "explain"), True),
        AddonAction("Load session", (*base, "--load"), True),
        AddonAction("Clear diagnostics", (*base, "clear-diagnostics"), False),
        AddonAction("Doctor", (*base, "doctor"), True),
    )


def render_action_script(
    action: AddonAction,
    *,
    terminal_command: Sequence[str] | None = None,
) -> str:
    command_literal = "[" + ", ".join(_groovy_string(part) for part in action.command) + "]"
    terminal = tuple(terminal_command or _DEFAULT_TERMINAL)
    terminal_literal = "[" + ", ".join(_groovy_string(part) for part in terminal) + "]"
    open_terminal = "true" if action.open_terminal else "false"
    return (
        f"""
// Generated by tmux-mindmap addon helper
// Menu title: {action.name}

def cmd = {command_literal}.collect {{ it.toString() }}
def terminalCmd = {terminal_literal}.collect {{ it.toString() }}
def finalCmd = new ArrayList<String>()
if ({open_terminal}) {{
  finalCmd.addAll(terminalCmd)
}}
finalCmd.addAll(cmd)
new ProcessBuilder(finalCmd)
  .redirectErrorStream(true)
  .start()
""".strip()
        + "\n"
    )


def write_addon_scripts(directory: Path, *, binary_command: Sequence[str]) -> list[Path]:
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for action in build_addon_actions(binary_command):
        filename = action.name.lower().replace(" ", "-") + ".groovy"
        path = directory / filename
        path.write_text(render_action_script(action), encoding="utf-8")
        written.append(path)
    return written
