// Generated by tmux-mindmap addon helper
// Menu title: Clear diagnostics

def cmd = ['freeplane-tmux', 'clear-diagnostics'].collect { it.toString() }
def terminalCmd = ['x-terminal-emulator', '-e'].collect { it.toString() }
def finalCmd = new ArrayList<String>()
if (false) {
  finalCmd.addAll(terminalCmd)
}
finalCmd.addAll(cmd)
new ProcessBuilder(finalCmd)
  .redirectErrorStream(true)
  .start()
