// Generated by tmux-mindmap addon helper
// Menu title: Load session

def cmd = ['freeplane-tmux', '--load'].collect { it.toString() }
def terminalCmd = ['x-terminal-emulator', '-e'].collect { it.toString() }
def finalCmd = new ArrayList<String>()
if (true) {
  finalCmd.addAll(terminalCmd)
}
finalCmd.addAll(cmd)
new ProcessBuilder(finalCmd)
  .redirectErrorStream(true)
  .start()
